# Generated by Django 3.0.8 on 2020-09-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200926_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
