# Generated by Django 3.0.8 on 2021-01-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_auto_20210109_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='username',
        ),
    ]
