# Generated by Django 3.0.8 on 2021-01-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_auto_20210109_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='user',
            new_name='username',
        ),
    ]
