# Generated by Django 3.0.8 on 2021-01-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_auto_20210109_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
