# Generated by Django 3.0.8 on 2021-01-30 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0028_auto_20210117_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='who_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
